# coding=utf-8
import unittest

"""389. Find the Difference
https://leetcode.com/problems/find-the-difference/description/

Given two strings **_s_** and **_t_** which consist of only lowercase letters.

String **_t_** is generated by random shuffling string **_s_** and then add
one more letter at a random position.

Find the letter that was added in **_t_**.

**Example:**

    
    
    Input:
    s = "abcd"
    t = "abcde"
    
    Output:
    e
    
    Explanation:
    'e' is the letter that was added.


Similar Questions:
  Single Number (single-number)
"""

from collections import defaultdict
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        cache = defaultdict(int)
        for c in s:
            cache[c] += 1
        for c in t:
            if c in cache:
                cache[c] -= 1
                if cache[c] == 0:
                    cache.pop(c)
            else:
                return c
        return cache.pop()


class T(unittest.TestCase):
    def test(self):
        s = Solution()
        self.assertEqual(s.findTheDifference("abcd", "abcde"), "e")


if __name__ == "__main__":
    unittest.main()
