# coding=utf-8
import unittest

"""Find the Difference
https://leetcode.com/problems/find-the-difference/description/

<p>
Given two strings <b><i>s</i></b> and <b><i>t</i></b> which consist of only lowercase letters.</p>

<p>String <b><i>t</i></b> is generated by random shuffling string <b><i>s</i></b> and then add one more letter at a random position.</p>

<p>Find the letter that was added in <b><i>t</i></b>.</p>

<p><b>Example:</b>
<pre>
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
</pre>
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        

    def test(self):
        pass


if __name__ == "__main__":
    unittest.main()
