"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
from __future__ import print_function


def fibonacci(stop=-1):
    """generating fibonacci sequence

    :param length: length of fibonacci
    :param stop: maximum value
    :return: fibonacci sequence
    """
    a, b = 1, 1
    yield a
    while True:
        yield b
        a, b = b, a + b

        if 0 < stop < b:
            break


if __name__ == '__main__':
    print(sum(i for i in fibonacci(4000000) if i % 2 == 0))  # 4613732
