#!/usr/bin/env python
# coding=utf-8
"""
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
D?
"""
from __future__ import print_function


def pentagonal_number(start=1, count=-1):
    """pentagonal sequence

    :param count:
    :return:
    """
    while count != 0:
        pentagonal_number.func_dict['n'] = start

        count -= 1
        yield start * (3 * start - 1) / 2
        start += 1


if __name__ == '__main__':
    pentagonal = list(i for i in pentagonal_number(count=10000))
    caches = set(pentagonal)

    for i in pentagonal:
        for j in pentagonal:
            if j >= i:
                break

            if i + j in caches and i - j in caches:
                print(i, j, i - j)  # 5482660
