#!/usr/bin/env python
# coding=utf-8

"""45. Triangular, pentagonal, and hexagonal
https://projecteuler.net/problem=45

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle |  | T _n_ = _n_ ( _n_ +1)/2 |  | 1, 3, 6, 10, 15, ...  
---|---|---|---|---  
Pentagonal |  | P _n_ = _n_ (3 _n_ −1)/2 |  | 1, 5, 12, 22, 35, ...  
Hexagonal |  | H _n_ = _n_ (2 _n_ −1) |  | 1, 6, 15, 28, 45, ...  
  
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
